---
jobs:
- name: deploy-web-app
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - put: cf
    params:
      manifest: /code/manifest.yml

resources:
- name: code
  type: git
  source:
    uri: {{git-repo}}

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
